# Generated by Django 5.1.4 on 2025-01-10 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.CharField(max_length=30)),
                ('initial_weight', models.FloatField(help_text='Enter a positive number', validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
