# Generated by Django 5.1.4 on 2025-01-10 15:02

import django.core.validators
import django.db.models.deletion
import tracker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='date_of_birth',
            field=models.DateField(help_text="Enter the measurement's date", validators=[tracker.validators.validate_not_in_future]),
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text="Enter the measurement's date", validators=[tracker.validators.validate_not_in_future])),
                ('weight', models.FloatField(help_text='Enter a positive number', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to='tracker.cat')),
            ],
        ),
    ]
