# Generated by Django 5.1.4 on 2025-01-10 16:11

import tracker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_cat_date_of_birth_weightentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightentry',
            options={'verbose_name_plural': 'weight entries'},
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(auto_now_add=True, help_text="Enter the measurement's date", validators=[tracker.validators.validate_not_in_future]),
        ),
    ]
