# Generated by Django 5.1.2 on 2025-01-18 12:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_weightentry_options_alter_weightentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='weight',
            field=models.FloatField(help_text='Enter a positive number (in kg)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
